### ISSUE TITLE
No save bug when compiling with Ruby >2.3

### ISSUE THREAD

**Issue by Yummychickenblue** [vinyldarkscratch/synglechance#24]
I just wanted to mention that I've played through the first act (Barrens) of the game while quitting and reloading the application with no save issues to speak of. I have compiled the engine on Ruby `MRIVERSION=2.5`. This was on a Linux system, so I don't know if the bug only affects MacOS or if it's been resolved.

**Comment by vinyldarkscratch** [comment]
@Yummychickenblue Thank you for the update!  Perhaps it's just macOS in that case -- will take a look into once my MacBook is repaired.  :wink:

**Comment by vinyldarkscratch** [comment]
I'm happy to say that something has changed in SyngleChance for the better.  I don't seem to be having that nasty save issue anymore.  So, Ruby 2.5 on macOS, here we come!
