### ISSUE TITLE
Unable to open 'Data/xScripts.rxdata'

### ISSUE THREAD

**Issue by levellozo** [vinyldarkscratch/synglechance#6]
The solution given (dragging the files out and back again) is not working for me! :( Is there something I might be doing wrong?

**Comment by vinyldarkscratch** [comment]
Hey there, based upon the troubleshooting technique you used, I'm going to assume that you're on macOS.  I think I know what's going on, so I'm going to ask a few questions:

1) What version of macOS are you running?
2) What OneShot macOS release are you using?  (Latest is 1.0.2!)
3) Do you have Steam running while you're opening the game?

**Comment by levellozo** [comment]
Hey! :)

1. It's High Sierra (10.13.3)
2. Tehehe, I had the 1.0.1! But did the process with the 1.0.2 and have the same Unable to open 'Data/xScripts.rxdata' issue :(
3. Yes! Shouldn't I?

**Comment by vinyldarkscratch** [comment]
Ah, I see, it's something different than what I was expecting!  Hearing that you've got the "Unable to open 'Data/xScripts.rxdata'" issue changes things.  The troubleshooting technique wasn't one that I had actually ever tried myself -- it was suggested by another user -- let me check on something on my end real quick?

**Comment by vinyldarkscratch** [comment]
(Especially since I've only been testing on my own computer, and haven't had another computer to test with...)  Can you open a Finder window, press ⇧⌘G, paste `~/Library/Application Support/Steam/SteamApps/common/OneShot/` and hit enter, then take a screenshot (⇧⌘4, Space, click on the window -- screenshot file on your desktop) and send it here?

**Comment by levellozo** [comment]
<img width="1179" alt="screen shot 2018-02-28 at 17 33 40" src="https://user-images.githubusercontent.com/36927010/36811727-902ffe10-1cad-11e8-956f-44469212286f.png">

Sure thing!

**Comment by vinyldarkscratch** [comment]
Thank you!  What I'm seeing here is that you're missing a number of core files needed to run the game.  You should have the following folders as well (I removed all those .dll and .exe files on my end, but don't worry about 'em):

<img width="882" alt="screen shot 2018-02-28 at 12 35 29" src="https://user-images.githubusercontent.com/5179191/36811904-47c6c358-1c84-11e8-9b92-2ddd6feb8c32.png">

It seems like Steam didn't complete it's download.  What I would do is the following:

1. Uninstall the game through Steam's GUI.
2. Go back to this folder and delete _all_ remaining files.
3. Close Steam.
4. Follow the instructions to download OneShot through SteamCMD again, as described on the [release page](https://github.com/vinyldarkscratch/synglechance/releases/tag/v1.0.2).
5. Re-open Steam.
6. Re-install the macOS port through double-clicking `install.command`.

If this doesn't work, please let me know and I'll do what I can to help!

**Comment by levellozo** [comment]
Okay! I'll do this right now and tell you what happens in a bit!

Thanks for the support! <3

**Comment by levellozo** [comment]
Okay, bad news...

<img width="1274" alt="screen shot 2018-02-28 at 17 53 26" src="https://user-images.githubusercontent.com/36927010/36812566-5435fe16-1cb0-11e8-9948-7ec6ceb6e1c6.png">

**Comment by vinyldarkscratch** [comment]
I see, hmm...  Luckily we're getting somewhere though!

Can you screenshot what's inside the Data folder if you scroll all the way down?  (I might have made a small mistake in the install script, sorry about that!)

**Comment by vinyldarkscratch** [comment]
Hmm, if you replaced the file and it's still giving you that error...  I honestly am somewhat stumped on this one, especially since another user is saying that everything seems to be working.

It's possible that we're just forgetting about something somewhere.  Is it possible that we can get in touch on a different platform and do a screenshare-type thing, like Skype, Google Hangouts, Telegram, etc.?  (You can find me on Skype and Telegram at `vinyldarkscratch`, or Google Hangouts at dark.tailed.wolf@gmail.com!)

**Comment by levellozo** [comment]
Damn, why was I the chosen one to give you trouble?! hahaha

I have to go out in a bit, but I'll definitely reach out to you tomorrow, okay?

Thanks again for the help!

**Comment by vinyldarkscratch** [comment]
Hehe, you're one of the few who have seen this and have a macOS -- so, you could say that you're one of the early access testers in a sense~  It's not a problem at all, I'm happy to help!  Sounds good, I shall be around tomorrow.  ;)

**Comment by vinyldarkscratch** [comment]
Looks like we might not even need to do that -- I just tried to launch the game, and I'm now running into the same issue!

**Comment by vinyldarkscratch** [comment]
Due to the fact that the current release has a ton of hindering issues, I'm going to close this issue.  Stay tuned for the official 1.0.0 release, and if it still happens in that one, please let me know and I'll do my best to fix it!
